from .rust_bindings import (
    STRIP_WHITESPACE_DO_NOT_MINIFY_DOCTYPE,
    STRIP_WHITESPACE_ENSURE_SPEC_CONPLIANT_UNQUOTED_ATTRIBUTE_VALUES,
    STRIP_WHITESPACE_KEEP_CLOSING_TAGS,
    STRIP_WHITESPACE_KEEP_COMMENTS,
    STRIP_WHITESPACE_KEEP_HTML_AND_HEAD_OPENING_TAGS,
    STRIP_WHITESPACE_KEEP_SPACES_BETWEEN_ATTRIBUTES,
    STRIP_WHITESPACE_MINIFY_CSS,
    STRIP_WHITESPACE_MINIFY_JS,
    STRIP_WHITESPACE_REMOVE_BANGS,
    STRIP_WHITESPACE_REMOVE_PROCESSING_INSTRUCTIONS,
)
